# Generated by Django 5.2.8 on 2025-12-06 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=60, null=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('motive', models.CharField(blank=True, max_length=40, null=True)),
                ('rate_sendero', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate_info', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate_limpieza', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate_personal', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_positivo', models.TextField(blank=True, null=True)),
                ('comentario_negativo', models.TextField(blank=True, null=True)),
                ('nps', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario_general', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=True, help_text='Si True, no se almacena información identificable')),
                ('consent_given', models.BooleanField(default=False, help_text='Consentimiento explícito para usar datos')),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('topics', models.JSONField(blank=True, help_text='Array de tópicos extraídos o tokens relevantes', null=True)),
                ('score_text', models.FloatField(blank=True, help_text='score de positividad/algún algoritmo', null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='administracion.period')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='administracion.sector')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatsPerPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('participation_rate', models.FloatField(blank=True, help_text='responses / visits', null=True)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('avg_nps', models.FloatField(blank=True, null=True)),
                ('sentiment_index', models.FloatField(blank=True, help_text='p.ej. (pos-neg)/total o %pos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='administracion.period')),
            ],
            options={
                'verbose_name': 'Estadísticas por periodo',
                'verbose_name_plural': 'Estadísticas por periodos',
            },
        ),
        migrations.CreateModel(
            name='TopIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 = top problema')),
                ('frequency', models.PositiveIntegerField(blank=True, help_text='veces reportado (por cálculo)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_issues', to='administracion.period')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_issue_entry', to='administracion.response')),
            ],
            options={
                'verbose_name': 'Problema destacado',
                'verbose_name_plural': 'Problemas destacados',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TopPositiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='1 = top')),
                ('score', models.FloatField(blank=True, help_text='Score de relevancia/positividad', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_positive_comments', to='administracion.period')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_positive_entry', to='administracion.response')),
            ],
            options={
                'verbose_name': 'Comentario positivo destacado',
                'verbose_name_plural': 'Comentarios positivos destacados',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField(default=0, help_text='Número de visitas en el periodo (ej. total mensual)')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_counts', to='administracion.period')),
            ],
            options={
                'verbose_name': 'Conteo de visitas',
                'verbose_name_plural': 'Conteos de visitas',
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created_at'], name='administrac_created_66452a_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['period'], name='administrac_period__8c3a47_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['sector'], name='administrac_sector__e225ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topissue',
            unique_together={('response', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='toppositivecomment',
            unique_together={('response', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='visitcount',
            unique_together={('period',)},
        ),
    ]
